---
output: html_document
editor_options:
chunk_output_type: console
---

# Legal Notices

## Disclaimer

TDMore has been created for personal use only. The use of any result generated by TDMore is in any case the sole risk and responsibility of the TDMore user. Therapeutic decision should not solely rely on TDMore as information provided by TDMore does not replace clinical judgement. Although TDMore has been validated carefully, there is no guarantee for the accuracy of the provided results. When using TDMore you automatically agree with this disclaimer and the legal notices.

## Content
The authors reserve the right not to be responsible for the topicality, correctness, completeness or quality of the information provided. Liability claims regarding damage caused by the use of any information provided, including any kind of information which is incomplete or incorrect, will therefore be rejected. 
All offers are not-binding and without obligation. Parts of the pages or the complete publication including all offers and information might be extended, changed or partly or completely deleted by the authors without separate announcement.

## Referrals and links
The authors are not responsible for any contents linked or referred to from these pages - unless they have full knowledge of illegal contents and would be able to prevent the visitors of this site fromviewing those pages. If any damage occurs by the use of information presented there, only the author of the respective pages might be liable, not the one who has linked to these pages. Furthermore the authors are not liable for any postings or messages published by users of discussion boards, guestbooks or mailinglists provided on these pages.

## Copyright
All work is under exclusive copyright by KULeuven and cannot be distributed or modified.
You are allowed to install this package for experimentation. Please <a href="mailto:ruben.faelens@kuleuven.be">contact the authors</a> to obtain a license to use this work in a commercial software, or for research. 

## Legal validity of this disclaimer
This disclaimer is to be regarded as part of the internet publication which you were referred from. If sections or individual terms of this statement are not legal or correct, the content or validity of the other parts remain uninfluenced by this fact.

The text of this disclaimer is based on the services of http://www.disclaimer.de

